Movie.create(title: "Watchmen", year: 2019, plot: "Set in an alternate history where masked vigilantes are treated as outlaws, Watchmen embraces the nostalgia of the original groundbreaking graphic novel of the same name, while attempting to break new ground of its own.")
Movie.create(title: "The Unbearable Weight of Massive Talent", year: 2022, plot: "Moviestar Nick Cage is channeling his iconic characters as he's caught between a superfan and a CIA agent.")
Movie.create(title: "Almost Famous", year: 2000, plot: "A high-school boy in the early 1970s is given the chance to write a story for Rolling Stone magazine about an up-and-coming rock band as he accompanies them on their concert tour.")
Movie.create(title: "Tron: Legacy", year: 2010, plot: "The son of a virtual world designer goes looking for his father and ends up inside the digital world that his father designed. He meets his father's corrupted creation and a unique ally who was born inside the digital world.")
Movie.create(title: "Up in the Air", year: 2009, plot: "Ryan's job is to travel around the country firing off people. When his boss hires Natalie, who proposes firing people via video conference, he tries to convince her that her method is a mistake.")

Actor.create(movie_id: 1, first_name: "Regina", last_name: "King", known_for: "Watchmen")
Actor.create(movie_id: 2, first_name: "Nicolas", last_name: "Cage", known_for: "The Unbearable Weight of Massive Talent")
Actor.create(movie_id: 2, first_name: "Pedro", last_name: "Pascal", known_for: "Game of Thrones")
Actor.create(movie_id: 3, first_name: "Frances", last_name: "McDormand", known_for: "Almost Famous")
Actor.create(movie_id: 4, first_name: "Jeff", last_name: "Bridges", known_for: "Tron: Legacy")
Actor.create(movie_id: 5, first_name: "Vera", last_name: "Farmiga", known_for: "Up in the Air")
Actor.create(movie_id: 5, first_name: "George", last_name: "Clooney", known_for: "ER")
