Actor.create(first_name: "Regina", last_name: "King", known_for: "Watchmen")
Actor.create(first_name: "Nicolas", last_name: "Cage", known_for: "The Unbearable Weight of Massive Talent")
Actor.create(first_name: "Frances", last_name: "McDormand", known_for: "Almost Famous")
Actor.create(first_name: "Jeff", last_name: "Bridges", known_for: "Tron: Legacy")
Actor.create(first_name: "Vera", last_name: "Farmiga", known_for: "Up in the Air")
